"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tenant-service-change-me-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    # Local apps
    'tenants',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Doit être en premier
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Cette base est le "control plane" : elle contient uniquement le Tenant
# Registry (métadonnées des établissements). Elle est distincte des bases
# métier par tenant qui seront introduites en Phase 5 (Tenant Database
# Management) — ce service ne doit jamais héberger de données métier.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tenant_registry_db',
        'USER': 'tenant_user',
        'PASSWORD': 'password',
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Jeton partagé pour la communication interne Gateway → Tenant Service
# (voir tenants.permissions.IsInternalService). Jamais de valeur en dur ici :
# non défini = accès refusé par défaut sur GET /tenants/resolve/.
TENANT_SERVICE_INTERNAL_TOKEN = os.environ.get('TENANT_SERVICE_INTERNAL_TOKEN', '')

# Phase 7 (Tenant Provisioning) : URL du service PERSONNEL, seul service
# disposant aujourd'hui d'un mécanisme de Dynamic Database Routing
# (Phase 6) et donc du endpoint interne symétrique
# POST /api/internal/provision-database/. Voir tenants/provisioning.py
# (PROVISIONING_CAPABLE_SERVICES) — étendre à un autre service consiste
# à lui donner l'équivalent de la Phase 6 puis à ajouter une entrée ici,
# jamais à modifier la logique d'orchestration elle-même.
PROVISIONING_SERVICE_PERSONNEL_URL = os.environ.get(
    'PROVISIONING_SERVICE_PERSONNEL_URL', 'http://fultang-personnel:8000',
)
# Medical-Monitoring : même mécanisme, une fois doté de l'équivalent Phase 6
# (core/tenant_routing/) et de son endpoint interne symétrique de provisioning.
PROVISIONING_SERVICE_MEDICAL_URL = os.environ.get(
    'PROVISIONING_SERVICE_MEDICAL_URL', 'http://fultang-medical-backend:8000',
)
# Phase 8 (finalisation multi-tenance) : fultang-compta-financiere,
# ComptaMatiere et Gestion-Infrastructures reçoivent à leur tour un
# tenant_routing/ symétrique à celui de service-personnel/Medical-Monitoring
# — voir tenants/provisioning.py (PROVISIONING_CAPABLE_SERVICES).
PROVISIONING_SERVICE_COMPTA_URL = os.environ.get(
    'PROVISIONING_SERVICE_COMPTA_URL', 'http://fultang-compta-financiere-backend:8000',
)
PROVISIONING_SERVICE_COMPTA_MATIERE_URL = os.environ.get(
    'PROVISIONING_SERVICE_COMPTA_MATIERE_URL', 'http://fultang-compta-matiere-backend:8000',
)
PROVISIONING_SERVICE_INFRASTRUCTURE_URL = os.environ.get(
    'PROVISIONING_SERVICE_INFRASTRUCTURE_URL', 'http://fultang-infrastructure-web:8000',
)
PROVISIONING_TIMEOUT_SECONDS = int(os.environ.get('PROVISIONING_TIMEOUT_SECONDS', '30'))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import sys
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test_db.sqlite3',
    }

REST_FRAMEWORK = {
    # La Gateway valide le JWT et injecte X-User-ID / X-User-Roles.
    # On fait confiance à ces headers plutôt que de re-vérifier le JWT.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'config.authentication.GatewayHeaderAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Microservice Tenant Management API',
    'DESCRIPTION': 'API du Tenant Registry — gestion des établissements de santé (métadonnées uniquement).',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Swagger pointe vers la Gateway avec le préfixe /tenants
    'SERVERS': [
        {
            'url': 'http://localhost:8080/tenants',
            'description': 'API Gateway (Point d\'entrée principal — Auth JWT requise)',
        },
    ],
    'SECURITY': [{'BearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'BearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'Token JWT obtenu via POST /auth/login sur la Gateway (http://localhost:8080)',
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
    },
}

# Configuration CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8080",
]
