# Generated by Django 4.2.7 on 2025-12-18 20:43
#
# Phase 8 (tenant_routing) : la dépendance à settings.AUTH_USER_MODEL et la
# ForeignKey correspondante ont été retirées de cette migration historique.
# Le champ `idPersonnel_emetteur` a de toute façon fini par devenir un
# CharField (voir 0011_remove_archiveinventaire_responsable_and_more.py) —
# le modèle actuel (apps/comptabilite_matiere/models/besoin.py) n'a jamais
# été une ForeignKey vers auth_user. Rejouer cette migration SANS la FK sur
# une base tenant fraîche évite un `ProgrammingError: relation "auth_user"
# does not exist` (auth_user n'existe volontairement que sur 'default' —
# voir tenant_routing/router.py). Aucun changement pour 'default' : cette
# migration y est déjà appliquée, modifier son contenu ne la rejoue pas.

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Besoin",
            fields=[
                (
                    "idBesoin",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant du besoin",
                    ),
                ),
                (
                    "date_creation_besoin",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date et heure de création du besoin (automatique)",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        help_text="Justification du besoin", verbose_name="Motif"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NON_TRAITE", "Non Traité"),
                            ("EN_COURS", "En Cours"),
                            ("TRAITE", "Traité"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_COURS",
                        help_text="État actuel du besoin",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_traitement_directeur",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure du traitement par le directeur",
                        null=True,
                        verbose_name="Date de traitement",
                    ),
                ),
                (
                    "commentaire_directeur",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire du directeur sur le besoin",
                        null=True,
                        verbose_name="Commentaire du directeur",
                    ),
                ),
                (
                    "idPersonnel_emetteur",
                    models.CharField(
                        max_length=36,
                        help_text="Référence vers le personnel ayant émis le besoin",
                        verbose_name="Personnel émetteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besoin",
                "verbose_name_plural": "Besoins",
                "db_table": "comptabilite_matiere_besoin",
                "ordering": ["-date_creation_besoin"],
            },
        ),
    ]
