# Generated by Django 4.2.7 on 2025-12-18 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Besoin",
            fields=[
                (
                    "idBesoin",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant du besoin",
                    ),
                ),
                (
                    "date_creation_besoin",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date et heure de création du besoin (automatique)",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        help_text="Justification du besoin", verbose_name="Motif"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NON_TRAITE", "Non Traité"),
                            ("EN_COURS", "En Cours"),
                            ("TRAITE", "Traité"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_COURS",
                        help_text="État actuel du besoin",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_traitement_directeur",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure du traitement par le directeur",
                        null=True,
                        verbose_name="Date de traitement",
                    ),
                ),
                (
                    "commentaire_directeur",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire du directeur sur le besoin",
                        null=True,
                        verbose_name="Commentaire du directeur",
                    ),
                ),
                (
                    "idPersonnel_emetteur",
                    models.ForeignKey(
                        help_text="Référence vers le personnel ayant émis le besoin",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="besoins_emis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Personnel émetteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besoin",
                "verbose_name_plural": "Besoins",
                "db_table": "comptabilite_matiere_besoin",
                "ordering": ["-date_creation_besoin"],
            },
        ),
    ]
