# Generated by Django 4.2.7 on 2025-12-18 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_matiere", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materiel",
            fields=[
                (
                    "idMateriel",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant du matériel",
                    ),
                ),
                (
                    "nom_Materiel",
                    models.CharField(
                        help_text="Nom descriptif du matériel",
                        max_length=200,
                        verbose_name="Nom du matériel",
                    ),
                ),
                (
                    "prix_achat_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix d'achat par unité (en FCFA)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Prix d'achat unitaire",
                    ),
                ),
                (
                    "quantite_stock",
                    models.IntegerField(
                        default=0,
                        help_text="Quantité actuellement disponible en stock",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantité en stock",
                    ),
                ),
                (
                    "date_derniere_modification",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de la dernière modification (automatique)",
                        verbose_name="Date de dernière modification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matériel",
                "verbose_name_plural": "Matériels",
                "db_table": "comptabilite_matiere_materiel",
                "ordering": ["nom_Materiel"],
            },
        ),
        migrations.CreateModel(
            name="MaterielDurable",
            fields=[
                (
                    "materiel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="comptabilite_matiere.materiel",
                    ),
                ),
                (
                    "Etat",
                    models.CharField(
                        choices=[
                            ("EN_BON_ETAT", "En Bon État"),
                            ("EN_REPARATION", "En Réparation"),
                        ],
                        default="EN_BON_ETAT",
                        help_text="État actuel du matériel",
                        max_length=20,
                        verbose_name="État",
                    ),
                ),
                (
                    "localisation",
                    models.CharField(
                        help_text="Emplacement actuel du matériel dans l'hôpital",
                        max_length=200,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "date_Enregistrement",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date d'enregistrement initial du matériel (automatique)",
                        verbose_name="Date d'enregistrement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matériel Durable",
                "verbose_name_plural": "Matériels Durables",
                "db_table": "comptabilite_matiere_materiel_durable",
                "ordering": ["nom_Materiel"],
            },
            bases=("comptabilite_matiere.materiel",),
        ),
        migrations.CreateModel(
            name="MaterielMedical",
            fields=[
                (
                    "materiel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="comptabilite_matiere.materiel",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("MEDICAMENT", "Médicament"),
                            ("CONSOMMABLE", "Consommable"),
                            ("REACTIF", "Réactif"),
                        ],
                        help_text="Type de matériel médical",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "unite_mesure",
                    models.CharField(
                        choices=[
                            ("BOITE", "Boîte"),
                            ("FLACON", "Flacon"),
                            ("UNITE", "Unité"),
                            ("PLAQUETTE", "Plaquette"),
                        ],
                        help_text="Unité dans laquelle le matériel est compté",
                        max_length=20,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "prix_vente_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de vente par unité (en FCFA)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Prix de vente unitaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matériel Médical",
                "verbose_name_plural": "Matériels Médicaux",
                "db_table": "comptabilite_matiere_materiel_medical",
                "ordering": ["nom_Materiel"],
            },
            bases=("comptabilite_matiere.materiel",),
        ),
    ]
