# Generated by Django 4.2.7 on 2025-12-18 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comptabilite_matiere", "0002_materiel_materieldurable_materielmedical"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "idLivraison",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de la livraison",
                    ),
                ),
                (
                    "bon_livraison_numero",
                    models.CharField(
                        help_text="Numéro du bon de livraison fourni par le fournisseur",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro du bon de livraison",
                    ),
                ),
                (
                    "nom_fournisseur",
                    models.CharField(max_length=200, verbose_name="Nom du fournisseur"),
                ),
                (
                    "contact_fournisseur",
                    models.CharField(
                        help_text="Numéro de téléphone du fournisseur",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le contact doit contenir uniquement des chiffres, espaces, +, -, ( ou )",
                                regex="^[0-9+\\-\\s()]+$",
                            )
                        ],
                        verbose_name="Contact du fournisseur",
                    ),
                ),
                (
                    "date_reception",
                    models.DateTimeField(
                        help_text="Date et heure de réception de la livraison",
                        verbose_name="Date de réception",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de la livraison (en FCFA)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création de l'enregistrement (automatique)",
                        verbose_name="Date de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "db_table": "comptabilite_matiere_livraison",
                "ordering": ["-date_reception"],
            },
        ),
        migrations.CreateModel(
            name="Sortie",
            fields=[
                (
                    "idSortie",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de la sortie",
                    ),
                ),
                (
                    "numero_sortie",
                    models.CharField(
                        help_text="Numéro de référence unique de la sortie",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de sortie",
                    ),
                ),
                (
                    "date_sortie",
                    models.DateTimeField(
                        help_text="Date et heure de la sortie",
                        verbose_name="Date de sortie",
                    ),
                ),
                (
                    "motif_sortie",
                    models.CharField(
                        choices=[
                            ("VENTE", "Vente"),
                            ("UTILISATION_SERVICE", "Utilisation Service"),
                            ("DEFECTUEUX", "Défectueux"),
                            ("PERIME", "Périmé"),
                            ("PERTE", "Perte"),
                        ],
                        help_text="Raison de la sortie du matériel",
                        max_length=30,
                        verbose_name="Motif de sortie",
                    ),
                ),
                (
                    "idPersonnel",
                    models.ForeignKey(
                        help_text="Référence vers le personnel ayant effectué la sortie",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorties_effectuees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Personnel responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sortie",
                "verbose_name_plural": "Sorties",
                "db_table": "comptabilite_matiere_sortie",
                "ordering": ["-date_sortie"],
            },
        ),
    ]
