# Generated by Django 4.2.7 on 2025-12-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_matiere", "0003_livraison_sortie"),
    ]

    def gen_unique_codes(apps, schema_editor):
        Materiel = apps.get_model("comptabilite_matiere", "Materiel")
        for row in Materiel.objects.all():
            row.code_materiel = f"MAT-{row.pk}"
            row.save()

    operations = [
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("lu", "Lu"), ("non lu", "Non lu")],
                        default="non lu",
                        max_length=10,
                        verbose_name="Statut du rapport",
                    ),
                ),
                (
                    "objet",
                    models.CharField(max_length=255, verbose_name="Objet du rapport"),
                ),
                ("corps", models.TextField(verbose_name="Corps du rapport")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rapport",
                "verbose_name_plural": "Rapports",
                "db_table": "comptabilite_matiere_rapport",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="materiel",
            name="code_materiel",
            field=models.CharField(
                default="TEMP",
                help_text="Code unique d'identification du matériel",
                max_length=50,
                verbose_name="Code du matériel",
                null=True,
            ),
        ),
        migrations.RunPython(gen_unique_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="materiel",
            name="code_materiel",
            field=models.CharField(
                help_text="Code unique d'identification du matériel",
                max_length=50,
                unique=True,
                verbose_name="Code du matériel",
            ),
        ),
        migrations.CreateModel(
            name="LigneLivraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_materiel",
                    models.CharField(
                        choices=[("MEDICAL", "Medical"), ("DURABLE", "Durable")],
                        max_length=7,
                        verbose_name="Type de matériel",
                    ),
                ),
                ("quantite_conforme", models.PositiveIntegerField(default=0)),
                ("quantite_non_conforme", models.PositiveIntegerField(default=0)),
                (
                    "prix_unitaire_achat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date_peremption", models.DateField(blank=True, null=True)),
                (
                    "id_livraison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite_matiere.livraison",
                        verbose_name="Livraison",
                    ),
                ),
                (
                    "materiel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comptabilite_matiere.materiel",
                        verbose_name="Matériel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de livraison",
                "verbose_name_plural": "Lignes de livraison",
                "db_table": "comptabilite_matiere_ligne_livraison",
            },
        ),
    ]
