# Generated by Django 4.2.7 on 2025-12-22 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comptabilite_matiere", "0004_rapport_materiel_code_materiel_lignelivraison"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapport",
            name="id_personnel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rapports_materiels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Personnel",
            ),
        ),
    ]
