# Generated by Django 4.2.7 on 2025-12-22 15:10
#
# Phase 8 (tenant_routing) : ForeignKey vers settings.AUTH_USER_MODEL
# retirée (voir 0001_initial.py pour la justification — le champ finit de
# toute façon en CharField, voir
# 0011_remove_archiveinventaire_responsable_and_more.py).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_matiere", "0004_rapport_materiel_code_materiel_lignelivraison"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapport",
            name="id_personnel",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                verbose_name="Personnel",
            ),
        ),
    ]
