# Generated by Django 4.2.7 on 2025-12-24 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comptabilite_matiere", "0005_rapport_id_personnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapport",
            name="code_rapport",
            field=models.CharField(
                blank=True,
                help_text="Code unique (format: RPT-YYYY-XXX)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Code du rapport",
            ),
        ),
        migrations.AddField(
            model_name="rapport",
            name="date_envoi",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date et heure d'envoi du rapport",
                verbose_name="Date d'envoi",
            ),
        ),
        migrations.AddField(
            model_name="rapport",
            name="date_lecture",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de lecture du rapport",
                null=True,
                verbose_name="Date de lecture",
            ),
        ),
        migrations.AddField(
            model_name="rapport",
            name="destinataire",
            field=models.ForeignKey(
                blank=True,
                help_text="Personnel qui reçoit le rapport",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rapports_recus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinataire",
            ),
        ),
        migrations.AddField(
            model_name="rapport",
            name="est_lu",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le rapport a été lu",
                verbose_name="Lu",
            ),
        ),
        migrations.AddField(
            model_name="rapport",
            name="expediteur",
            field=models.ForeignKey(
                blank=True,
                help_text="Personnel qui envoie le rapport",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rapports_envoyes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="rapport",
            name="type_rapport",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Général"),
                    ("INVENTAIRE", "Inventaire"),
                    ("STOCK", "Stock"),
                    ("LIVRAISON", "Livraison"),
                ],
                default="GENERAL",
                help_text="Catégorie du rapport",
                max_length=15,
                verbose_name="Type de rapport",
            ),
        ),
        migrations.AlterField(
            model_name="rapport",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.CreateModel(
            name="PieceJointeRapport",
            fields=[
                (
                    "id_piece_jointe",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de la pièce jointe",
                    ),
                ),
                (
                    "type_piece",
                    models.CharField(
                        choices=[
                            ("ETAT_STOCK", "État du stock"),
                            ("ARCHIVE", "Archive"),
                            ("ANCIEN_STOCK", "Ancien stock"),
                            ("NOUVEAU_STOCK", "Nouveau stock"),
                            ("DIFFERENCES", "Différences"),
                            ("AUTRE", "Autre"),
                        ],
                        help_text="Type de la pièce jointe",
                        max_length=15,
                        verbose_name="Type de pièce",
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(
                        blank=True,
                        help_text="Nom du fichier attaché",
                        max_length=255,
                        null=True,
                        verbose_name="Nom du fichier",
                    ),
                ),
                (
                    "chemin_fichier",
                    models.CharField(
                        blank=True,
                        help_text="Chemin vers le fichier PDF sur le serveur",
                        max_length=500,
                        null=True,
                        verbose_name="Chemin du fichier",
                    ),
                ),
                (
                    "donnees_json",
                    models.JSONField(
                        blank=True,
                        help_text="Données stockées en format JSON",
                        null=True,
                        verbose_name="Données JSON",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "id_rapport",
                    models.ForeignKey(
                        help_text="Référence au rapport parent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_jointes",
                        to="comptabilite_matiere.rapport",
                        verbose_name="Rapport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "db_table": "comptabilite_matiere_piece_jointe_rapport",
                "ordering": ["id_rapport", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LigneSortie",
            fields=[
                (
                    "id_ligne_sortie",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de la ligne",
                    ),
                ),
                (
                    "code_materiel",
                    models.CharField(
                        help_text="Code d'identification du matériel",
                        max_length=50,
                        verbose_name="Code du matériel",
                    ),
                ),
                (
                    "nom_materiel",
                    models.CharField(
                        help_text="Nom du matériel sorti",
                        max_length=150,
                        verbose_name="Nom du matériel",
                    ),
                ),
                (
                    "type_materiel",
                    models.CharField(
                        choices=[("MEDICAL", "Médical"), ("DURABLE", "Durable")],
                        help_text="Type du matériel (médical ou durable)",
                        max_length=10,
                        verbose_name="Type de matériel",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        help_text="Quantité de matériel sortie",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix unitaire (pour les ventes)",
                        max_digits=12,
                        null=True,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "sous_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sous-total (quantité × prix, pour les ventes)",
                        max_digits=12,
                        null=True,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "id_materiel",
                    models.ForeignKey(
                        help_text="Référence au matériel sorti",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_sortie",
                        to="comptabilite_matiere.materiel",
                        verbose_name="Matériel",
                    ),
                ),
                (
                    "id_sortie",
                    models.ForeignKey(
                        help_text="Référence à la sortie parent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite_matiere.sortie",
                        verbose_name="Sortie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de sortie",
                "verbose_name_plural": "Lignes de sortie",
                "db_table": "comptabilite_matiere_ligne_sortie",
                "ordering": ["id_sortie", "id_ligne_sortie"],
            },
        ),
        migrations.CreateModel(
            name="LigneBesoin",
            fields=[
                (
                    "id_ligne_besoin",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de la ligne",
                    ),
                ),
                (
                    "materiel_nom",
                    models.CharField(
                        help_text="Nom du matériel demandé",
                        max_length=150,
                        verbose_name="Nom du matériel",
                    ),
                ),
                (
                    "quantite_demandee",
                    models.PositiveIntegerField(
                        help_text="Quantité de matériel demandée",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantité demandée",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("NORMAL", "Normale"),
                            ("HIGH", "Haute"),
                        ],
                        default="NORMAL",
                        help_text="Niveau de priorité de la demande",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "description_justification",
                    models.TextField(
                        blank=True,
                        help_text="Justification de la demande",
                        null=True,
                        verbose_name="Justification",
                    ),
                ),
                (
                    "quantite_accordee",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantité accordée après traitement (nullable avant traitement)",
                        null=True,
                        verbose_name="Quantité accordée",
                    ),
                ),
                (
                    "id_besoin",
                    models.ForeignKey(
                        help_text="Référence au besoin parent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite_matiere.besoin",
                        verbose_name="Besoin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de besoin",
                "verbose_name_plural": "Lignes de besoin",
                "db_table": "comptabilite_matiere_ligne_besoin",
                "ordering": ["id_besoin", "-priorite"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveInventaire",
            fields=[
                (
                    "id_archive",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de l'archive",
                    ),
                ),
                (
                    "code_archive",
                    models.CharField(
                        help_text="Code unique (format: ARC-YYYYMMDD-XX)",
                        max_length=20,
                        unique=True,
                        verbose_name="Code de l'archive",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date et heure de création de l'archive",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_termine",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de fin de l'inventaire",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_COURS",
                        help_text="État actuel de l'inventaire",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="Remarques générales sur l'inventaire",
                        null=True,
                        verbose_name="Observations",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Date de création enregistrement",
                    ),
                ),
                (
                    "rapport_associe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rapport lié à cet inventaire (optionnel)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives_liees",
                        to="comptabilite_matiere.rapport",
                        verbose_name="Rapport associé",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        help_text="Pharmacien responsable de l'inventaire",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archives_inventaire",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive d'inventaire",
                "verbose_name_plural": "Archives d'inventaire",
                "db_table": "comptabilite_matiere_archive_inventaire",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="rapport",
            name="archive_associee",
            field=models.ForeignKey(
                blank=True,
                help_text="Archive d'inventaire liée (pour rapports d'inventaire)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rapports",
                to="comptabilite_matiere.archiveinventaire",
                verbose_name="Archive associée",
            ),
        ),
        migrations.CreateModel(
            name="LigneArchiveInventaire",
            fields=[
                (
                    "id_ligne_archive",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de la ligne",
                    ),
                ),
                (
                    "code_materiel",
                    models.CharField(
                        help_text="Code d'identification du matériel",
                        max_length=50,
                        verbose_name="Code du matériel",
                    ),
                ),
                (
                    "nom_materiel",
                    models.CharField(
                        help_text="Nom du matériel",
                        max_length=150,
                        verbose_name="Nom du matériel",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix de vente du matériel",
                        max_digits=12,
                        null=True,
                        verbose_name="Prix de vente",
                    ),
                ),
                (
                    "quantite_ancien_stock",
                    models.PositiveIntegerField(
                        help_text="Quantité avant inventaire",
                        verbose_name="Ancien stock",
                    ),
                ),
                (
                    "quantite_nouveau_stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantité après inventaire (renseigné lors du comptage)",
                        null=True,
                        verbose_name="Nouveau stock",
                    ),
                ),
                (
                    "difference",
                    models.IntegerField(
                        blank=True,
                        help_text="Différence (nouveau - ancien)",
                        null=True,
                        verbose_name="Différence",
                    ),
                ),
                (
                    "statut_difference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCEDENT", "Excédent"),
                            ("DEFICIT", "Déficit"),
                            ("CONFORME", "Conforme"),
                        ],
                        help_text="Indique si excédent, déficit ou conforme",
                        max_length=10,
                        null=True,
                        verbose_name="Statut de la différence",
                    ),
                ),
                (
                    "id_archive",
                    models.ForeignKey(
                        help_text="Référence à l'archive parent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite_matiere.archiveinventaire",
                        verbose_name="Archive",
                    ),
                ),
                (
                    "id_materiel",
                    models.ForeignKey(
                        help_text="Référence au matériel",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_archive",
                        to="comptabilite_matiere.materiel",
                        verbose_name="Matériel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'archive d'inventaire",
                "verbose_name_plural": "Lignes d'archive d'inventaire",
                "db_table": "comptabilite_matiere_ligne_archive_inventaire",
                "ordering": ["id_archive", "nom_materiel"],
                "unique_together": {("id_archive", "id_materiel")},
            },
        ),
    ]
