# Generated by Django 4.2.7 on 2025-12-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "comptabilite_matiere",
            "0006_rapport_code_rapport_rapport_date_envoi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="besoin",
            name="statut",
            field=models.CharField(
                choices=[
                    ("NON_TRAITE", "Non Traité"),
                    ("EN_COURS", "En Cours"),
                    ("TRAITE", "Traité"),
                    ("REJETE", "Rejeté"),
                ],
                default="NON_TRAITE",
                help_text="État actuel du besoin",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
