# Generated by Django 4.2.7 on 2026-01-02 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "comptabilite_matiere",
            "0006_rapport_code_rapport_rapport_date_envoi_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sortie",
            name="heure_sortie",
            field=models.TimeField(
                blank=True,
                help_text="Heure de la sortie",
                null=True,
                verbose_name="Heure de sortie",
            ),
        ),
        migrations.AddField(
            model_name="sortie",
            name="montant_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant total de la sortie (pour les ventes)",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant total",
            ),
        ),
        migrations.AddField(
            model_name="sortie",
            name="observations",
            field=models.TextField(
                blank=True,
                help_text="Remarques sur la sortie",
                null=True,
                verbose_name="Observations",
            ),
        ),
        migrations.AddField(
            model_name="sortie",
            name="service_responsable",
            field=models.CharField(
                blank=True,
                help_text="Service effectuant la sortie",
                max_length=100,
                null=True,
                verbose_name="Service responsable",
            ),
        ),
    ]
