# Generated by Django 4.2.7 on 2026-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_matiere", "0007_add_sortie_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielmedical",
            name="unite_mesure",
            field=models.CharField(
                choices=[
                    ("BOITE", "Boîte"),
                    ("FLACON", "Flacon"),
                    ("UNITE", "Unité"),
                    ("PLAQUETTE", "Plaquette"),
                    ("SACHET", "Sachet"),
                    ("TUBE", "Tube"),
                ],
                help_text="Unité dans laquelle le matériel est compté",
                max_length=20,
                verbose_name="Unité de mesure",
            ),
        ),
    ]
