# Generated by Django 4.2.7 on 2026-01-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_matiere", "0007_alter_besoin_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignelivraison",
            name="code_materiel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Code d'identification du matériel",
                max_length=50,
                verbose_name="Code du matériel",
            ),
        ),
        migrations.AddField(
            model_name="lignelivraison",
            name="nom_materiel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom du matériel livré",
                max_length=150,
                verbose_name="Nom du matériel",
            ),
        ),
    ]
