# Generated by Django 4.2.7 on 2026-01-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_matiere", "0008_alter_materielmedical_unite_mesure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielmedical",
            name="unite_mesure",
            field=models.CharField(
                help_text="Unité dans laquelle le matériel est compté (ex: BOITE, FLACON, SACHET...)",
                max_length=50,
                verbose_name="Unité de mesure",
            ),
        ),
    ]
