# Generated by Django 4.2.7 on 2026-01-08 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_matiere", "0008_lignelivraison_code_materiel_and_more"),
        ("comptabilite_matiere", "0009_alter_materielmedical_unite_mesure"),
    ]

    operations = []
