# Generated by Django 6.0.3 on 2026-04-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite_matiere', '0010_merge_20260108_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveinventaire',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='expediteur',
        ),
        migrations.AddField(
            model_name='archiveinventaire',
            name='id_responsable',
            field=models.IntegerField(default=1, help_text="Identifiant du personnel responsable de l'inventaire", verbose_name='ID Responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='id_personnel_receptionnaire',
            field=models.IntegerField(blank=True, help_text='Identifiant du personnel ayant réceptionné la livraison', null=True, verbose_name='ID Personnel réceptionnaire'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='id_destinataire',
            field=models.IntegerField(blank=True, help_text='Identifiant du personnel qui reçoit le rapport', null=True, verbose_name='ID Destinataire'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='id_expediteur',
            field=models.IntegerField(blank=True, help_text='Identifiant du personnel qui envoie le rapport', null=True, verbose_name='ID Expéditeur'),
        ),
        migrations.AlterField(
            model_name='archiveinventaire',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='OUVERT', help_text="État actuel de l'inventaire", max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='idPersonnel_emetteur',
            field=models.IntegerField(help_text='Identifiant du personnel ayant émis le besoin', verbose_name='ID Personnel émetteur'),
        ),
        migrations.AlterField(
            model_name='materieldurable',
            name='Etat',
            field=models.CharField(choices=[('BON_ETAT', 'Bon État'), ('EN_REPARATION', 'En Réparation'), ('REFORME', 'Réformé')], default='BON_ETAT', help_text='État actuel du matériel', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='materielmedical',
            name='unite_mesure',
            field=models.CharField(choices=[('BOITE', 'Boîte'), ('FLACON', 'Flacon'), ('UNITE', 'Unité'), ('PLAQUETTE', 'Plaquette'), ('SACHET', 'Sachet'), ('TUBE', 'Tube')], help_text='Unité dans laquelle le matériel est compté (ex: BOITE, FLACON, SACHET...)', max_length=50, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_personnel',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Personnel'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='idPersonnel',
            field=models.IntegerField(help_text='Identifiant du personnel ayant effectué la sortie', verbose_name='ID Personnel responsable'),
        ),
    ]
