# Generated by Django 4.2.7 on 2026-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite_matiere', '0011_remove_archiveinventaire_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveinventaire',
            name='id_responsable',
            field=models.CharField(help_text="Identifiant du personnel responsable de l'inventaire", max_length=36, verbose_name='ID Responsable'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='idPersonnel_emetteur',
            field=models.CharField(help_text='Identifiant du personnel ayant émis le besoin', max_length=36, verbose_name='ID Personnel émetteur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='id_personnel_receptionnaire',
            field=models.CharField(blank=True, help_text='Identifiant du personnel ayant réceptionné la livraison', max_length=36, null=True, verbose_name='ID Personnel réceptionnaire'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_destinataire',
            field=models.CharField(blank=True, help_text='Identifiant du personnel qui reçoit le rapport', max_length=36, null=True, verbose_name='ID Destinataire'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_expediteur',
            field=models.CharField(blank=True, help_text='Identifiant du personnel qui envoie le rapport', max_length=36, null=True, verbose_name='ID Expéditeur'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_personnel',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='ID Personnel'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='idPersonnel',
            field=models.CharField(help_text='Identifiant du personnel ayant effectué la sortie', max_length=36, verbose_name='ID Personnel responsable'),
        ),
    ]
