# Generated by Django 6.0.3 on 2026-04-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(help_text='Numéro du compte selon le plan OHADA (ex: 706100)', max_length=10, unique=True, verbose_name='Numéro de compte')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('classe', models.CharField(choices=[('1', 'Classe 1 - Capitaux'), ('2', 'Classe 2 - Immobilisations'), ('3', 'Classe 3 - Stocks'), ('4', 'Classe 4 - Tiers'), ('5', 'Classe 5 - Trésorerie'), ('6', 'Classe 6 - Charges'), ('7', 'Classe 7 - Produits')], max_length=1, verbose_name='Classe')),
                ('type_compte', models.CharField(choices=[('produit', 'Produit'), ('charge', 'Charge'), ('actif', 'Actif'), ('passif', 'Passif'), ('tresorerie', 'Trésorerie')], max_length=20, verbose_name='Type de compte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('compte_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes', to='comptabilite.comptecomptable', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Compte Comptable',
                'verbose_name_plural': 'Comptes Comptables',
                'ordering': ['numero_compte'],
            },
        ),
    ]
