# Generated by Django 6.0.3 on 2026-04-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('sorties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text="Année de l'exercice (ex: 2026)", unique=True, verbose_name='Année')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=10, verbose_name='Statut')),
                ('resultat_net', models.DecimalField(blank=True, decimal_places=2, help_text='Calculé à la clôture : total produits (7) - total charges (6)', max_digits=15, null=True, verbose_name='Résultat net')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('cloture_par', models.IntegerField(blank=True, help_text="# EXT — ID de l'utilisateur ayant clôturé", null=True, verbose_name='Clôturé par')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Exercice Comptable',
                'verbose_name_plural': 'Exercices Comptables',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('JA', 'Journal des Achats'), ('JV', 'Journal des Ventes'), ('JC', 'Journal de Caisse'), ('JB', 'Journal de Banque'), ('JMM', 'Journal Mobile Money'), ('JOD', 'Journal des Opérations Diverses'), ('JRN', 'Journal de Report à Nouveau')], help_text='Code unique du journal (ex: JC, JB)', max_length=5, unique=True, verbose_name='Code journal')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('compte_contrepartie', models.ForeignKey(blank=True, help_text='Compte de trésorerie par défaut (571 pour JC, 521 pour JB, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_contrepartie', to='comptabilite.comptecomptable', verbose_name='Compte de contrepartie par défaut')),
            ],
            options={
                'verbose_name': 'Journal Comptable',
                'verbose_name_plural': 'Journaux Comptables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ecriture', models.CharField(editable=False, help_text='Auto-généré : EC-YYYY-NNNNN', max_length=20, unique=True, verbose_name="Numéro d'écriture")),
                ('date_ecriture', models.DateField(verbose_name="Date de l'écriture")),
                ('libelle', models.CharField(max_length=300, verbose_name="Libellé de l'écriture")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('piece_justificative', models.CharField(blank=True, help_text='Numéro de quittance, facture, bon de commande, etc.', max_length=100, null=True, verbose_name='Pièce justificative')),
                ('quittance_id', models.IntegerField(blank=True, help_text="# EXT — ID de la quittance dans l'app caisse", null=True, verbose_name='ID Quittance source')),
                ('bon_commande_id', models.IntegerField(blank=True, help_text="# EXT — ID du bon de commande dans l'app sorties", null=True, verbose_name='ID Bon de commande source')),
                ('ordre_paiement_id', models.IntegerField(blank=True, help_text="# EXT — ID de l'ordre de paiement dans l'app sorties", null=True, verbose_name='ID Ordre de paiement source')),
                ('created_by', models.IntegerField(blank=True, help_text="# EXT — ID de l'utilisateur ayant créé l'écriture", null=True, verbose_name='Créé par')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.exercicecomptable', verbose_name='Exercice comptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.journal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'verbose_name_plural': 'Écritures Comptables',
                'ordering': ['-date_ecriture', '-numero_ecriture'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Libellé de la ligne')),
                ('montant_debit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Montant débit')),
                ('montant_credit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Montant crédit')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='comptabilite.comptecomptable', verbose_name='Compte comptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecriturecomptable', verbose_name='Écriture')),
            ],
            options={
                'verbose_name': "Ligne d'Écriture",
                'verbose_name_plural': "Lignes d'Écriture",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrestationDeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique (ex: PREST-CONS-001)', max_length=20, unique=True, verbose_name='Code prestation')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_prestation', models.CharField(choices=[('consultation', 'Consultation'), ('hospitalisation', 'Hospitalisation'), ('laboratoire', 'Laboratoire'), ('imagerie', 'Imagerie'), ('pharmacie', 'Pharmacie'), ('soins', 'Soins'), ('chirurgie', 'Chirurgie'), ('autre', 'Autre')], max_length=20, verbose_name='Type de prestation')),
                ('service_hospitalier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service hospitalier')),
                ('service_hospitalier_id', models.IntegerField(blank=True, help_text='# EXT — ID du service dans le microservice Personnel', null=True, verbose_name='ID Service hospitalier')),
                ('tarif', models.DecimalField(decimal_places=2, help_text='Tarif de base en FCFA', max_digits=12, verbose_name='Tarif (FCFA)')),
                ('duree_min_jours', models.IntegerField(blank=True, help_text='Pour les paliers tarifaires (hospitalisation)', null=True, verbose_name='Durée minimale (jours)')),
                ('duree_max_jours', models.IntegerField(blank=True, help_text='Pour les paliers tarifaires (hospitalisation)', null=True, verbose_name='Durée maximale (jours)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('compte_comptable', models.ForeignKey(help_text='Compte de classe 7 pour cette prestation', on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='comptabilite.comptecomptable', verbose_name='Compte de produit associé')),
            ],
            options={
                'verbose_name': 'Prestation de Service',
                'verbose_name_plural': 'Prestations de Service',
                'ordering': ['type_prestation', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPrevisionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé du budget')),
                ('service_hospitalier', models.CharField(blank=True, help_text='Nom du service (ex: Laboratoire, Radiologie, Chirurgie)', max_length=100, null=True, verbose_name='Service hospitalier')),
                ('service_hospitalier_id', models.IntegerField(blank=True, help_text='# EXT — ID du service dans le microservice Personnel', null=True, verbose_name='ID Service hospitalier')),
                ('montant_prevu', models.DecimalField(decimal_places=2, help_text='Budget alloué en FCFA', max_digits=15, verbose_name='Montant prévu')),
                ('montant_consomme', models.DecimalField(decimal_places=2, default=0, help_text='Montant réellement dépensé', max_digits=15, verbose_name='Montant consommé')),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=10, verbose_name='Priorité')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='sorties.categoriesortie', verbose_name='Catégorie de dépense')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='comptabilite.exercicecomptable', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Budget Prévisionnel',
                'verbose_name_plural': 'Budgets Prévisionnels',
                'ordering': ['-exercice__annee', 'categorie'],
                'unique_together': {('exercice', 'categorie', 'service_hospitalier')},
            },
        ),
    ]
