# Generated by Django 6.0.3 on 2026-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_exercicecomptable_journal_ecriturecomptable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('utilisateur_id', models.IntegerField(blank=True, help_text="# EXT — ID de l'utilisateur ayant effectué l'action", null=True, verbose_name='ID Utilisateur')),
                ('utilisateur_nom', models.CharField(blank=True, help_text="Nom complet dénormalisé pour la piste d'audit", max_length=150, null=True, verbose_name='Nom utilisateur')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('validation', 'Validation'), ('annulation', 'Annulation'), ('cloture', 'Clôture'), ('suppression', 'Suppression')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(choices=[('compte_comptable', 'Compte Comptable'), ('journal', 'Journal'), ('ecriture', 'Écriture Comptable'), ('exercice', 'Exercice Comptable'), ('budget', 'Budget Prévisionnel'), ('prestation', 'Prestation de Service'), ('quittance', 'Quittance'), ('bon_commande', 'Bon de Commande'), ('ordre_paiement', 'Ordre de Paiement'), ('caisse', 'Caisse Journalière'), ('inventaire', 'Inventaire Caisse')], max_length=30, verbose_name='Module')),
                ('objet_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'objet concerné")),
                ('objet_reference', models.CharField(blank=True, help_text="Numéro d'écriture, de quittance, etc.", max_length=100, null=True, verbose_name='Référence')),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('donnees_avant', models.JSONField(blank=True, null=True, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, null=True, verbose_name='Données après modification')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['-date_action'], name='comptabilit_date_ac_ef0b76_idx'), models.Index(fields=['module', 'objet_id'], name='comptabilit_module_ceee2f_idx'), models.Index(fields=['utilisateur_id'], name='comptabilit_utilisa_8e3374_idx')],
            },
        ),
    ]
