# Generated by Django 6.0.3 on 2026-09-01 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformService",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Identifiant technique stable du service (ex: PERSONNEL). Utilisé par les futurs mécanismes de routing (Phase 6) — ne doit jamais changer une fois créé.",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code doit être en MAJUSCULES_SNAKE_CASE (ex: PERSONNEL, COMPTA_MATIERE).",
                                regex="^[A-Z][A-Z0-9_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom lisible du service (ex: Service Personnel).",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Actif"), ("INACTIVE", "Inactif")],
                        default="ACTIVE",
                        help_text="Statut du service dans le catalogue plateforme.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TenantDatabase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        help_text="Nom logique de la base dédiée à ce tenant pour ce service.",
                        max_length=100,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Hôte du serveur de base de données.", max_length=255
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=5432, help_text="Port du serveur de base de données."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente de provisioning"),
                            ("ACTIVE", "Actif"),
                            ("INACTIVE", "Inactif"),
                        ],
                        default="PENDING",
                        help_text="Statut logique de la configuration (voir docstring de classe).",
                        max_length=20,
                    ),
                ),
                (
                    "secret_reference",
                    models.CharField(
                        help_text="Référence opaque vers les credentials de connexion (ex: chemin dans un secret manager). Ne contient jamais le mot de passe lui-même.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service de la plateforme concerné (doit exister dans le catalogue PlatformService).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_databases",
                        to="tenants.platformservice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant auquel appartient cette configuration de base.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="databases",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant_id", "service_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "service"),
                        name="tenant_database_unique_tenant_service",
                    )
                ],
            },
        ),
    ]
