# Generated by Django 6.0.3 on 2026-09-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_seed_platform_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdatabase',
            name='last_error',
            field=models.CharField(blank=True, default='', help_text="Phase 7 : résumé lisible de la dernière erreur de provisioning (status=FAILED). Jamais un secret/credential — un message d'erreur technique court. Vide dès que le statut redevient ACTIVE ou PROVISIONING.", max_length=500),
        ),
        migrations.AlterField(
            model_name='tenantdatabase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de provisioning'), ('PROVISIONING', 'Provisioning en cours'), ('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('FAILED', 'Échec du provisioning')], default='PENDING', help_text='Statut logique de la configuration (voir docstring de classe).', max_length=20),
        ),
    ]
