# Generated by Django 6.0.3 on 2026-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_seed_platform_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_clinical_agent_export',
            field=models.BooleanField(default=True, help_text="Autorise ou non l'envoi des données médicales anonymisées de ce tenant vers clinical-agent / MedTutor. Par défaut True : un tenant existant avant l'introduction de ce champ conserve le comportement actuel après migration (aucune régression silencieuse de fonctionnalité). Source de vérité unique — clinical-agent interroge ce champ (via le Tenant Registry) avant toute lecture de données destinées à l'export, jamais après ; la logique de décision reste dans clinical-agent, ce champ n'est qu'une configuration."),
        ),
    ]
