# Generated by Django 6.0.3 on 2026-09-08 07:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_allow_clinical_agent_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalService',
            fields=[
                ('code', models.CharField(help_text='Identifiant technique stable du service fonctionnel (ex: PHARMACIE).', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Le code doit être en MAJUSCULES_SNAKE_CASE (ex: PHARMACIE, COMPTA_FINANCIERE).', regex='^[A-Z][A-Z0-9_]*$')])),
                ('name', models.CharField(help_text='Nom lisible du service fonctionnel (ex: Pharmacie).', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif')], default='ACTIVE', help_text='Statut du service dans le catalogue produit (ACTIVE = proposable aux tenants).', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans l'IHM (valeur la plus basse = affiché en premier).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, default='', help_text="Adresse postale de l'établissement (facultatif)."),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="Email de contact principal de l'établissement (facultatif).", max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text="URL du logo de l'établissement (facultatif, pas d'upload de fichier dans cette phase)."),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, default='', help_text="Numéro de téléphone principal de l'établissement (facultatif).", max_length=30),
        ),
        migrations.CreateModel(
            name='TenantFunctionalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='True si ce service fonctionnel est disponible pour ce tenant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_configs', to='tenants.functionalservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_services', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'service_id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'service'), name='tenant_functional_service_unique_tenant_service')],
            },
        ),
    ]
