# Generated by Django 6.0.3 on 2026-09-08 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_seed_functional_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, default='', max_length=100)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('TENANT_CREATED', 'Établissement créé'), ('TENANT_PROFILE_UPDATED', "Profil de l'établissement modifié"), ('TENANT_TECHNICAL_CONFIG_UPDATED', 'Configuration technique modifiée'), ('TENANT_STATUS_CHANGED', "Statut de l'établissement modifié"), ('TENANT_PROVISIONED', 'Provisioning déclenché'), ('TENANT_ADMIN_PROVISIONED', 'Compte administrateur provisionné'), ('TENANT_LOGO_UPDATED', 'Logo mis à jour'), ('TENANT_LOGO_REMOVED', 'Logo supprimé'), ('FUNCTIONAL_SERVICES_BULK_SET', 'Services configurés en masse'), ('FUNCTIONAL_SERVICE_TOGGLED', 'Service activé/désactivé')], max_length=50)),
                ('target_tenant_id', models.UUIDField(blank=True, null=True)),
                ('target_tenant_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de l'établissement, uploadé par le PlatformAdmin (Cycle de vie du tenant — Phase 2). Stockage disque local classique (FileSystemStorage, MEDIA_ROOT/MEDIA_URL), aucun object storage (S3/MinIO) n'existe encore dans FullTang — voir MULTITENANT_ARCHITECTURE.md pour la limite documentée (non partagé entre plusieurs instances du service).", null=True, upload_to='tenants/logos/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text="URL externe de secours pour le logo (facultatif). Si `logo` (fichier uploadé, voir ci-dessous) est renseigné, il prime toujours sur ce champ pour l'affichage — voir TenantSerializer.get_logo_display_url."),
        ),
    ]
