# Generated by Django 6.0.3 on 2026-09-12 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_adminactionlog_tenant_logo_alter_tenant_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('TENANT_CREATED', 'Établissement créé'), ('TENANT_PROFILE_UPDATED', "Profil de l'établissement modifié"), ('TENANT_TECHNICAL_CONFIG_UPDATED', 'Configuration technique modifiée'), ('TENANT_STATUS_CHANGED', "Statut de l'établissement modifié"), ('TENANT_DELETION_STARTED', 'Suppression définitive démarrée'), ('TENANT_DELETION_ARCHIVED', 'Archive de suppression validée'), ('TENANT_DELETION_CLEANED', 'Ressources physiques du tenant supprimées'), ('TENANT_DELETION_COMPLETED', 'Suppression définitive terminée'), ('TENANT_DELETION_FAILED', 'Suppression définitive échouée'), ('TENANT_PROVISIONED', 'Provisioning déclenché'), ('TENANT_ADMIN_PROVISIONED', 'Compte administrateur provisionné'), ('TENANT_LOGO_UPDATED', 'Logo mis à jour'), ('TENANT_LOGO_REMOVED', 'Logo supprimé'), ('FUNCTIONAL_SERVICES_BULK_SET', 'Services configurés en masse'), ('FUNCTIONAL_SERVICE_TOGGLED', 'Service activé/désactivé')], max_length=50),
        ),
        migrations.CreateModel(
            name='TenantDeletionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('tenant_identifier', models.CharField(max_length=100)),
                ('tenant_name', models.CharField(max_length=255)),
                ('initiated_by_id', models.CharField(blank=True, default='', max_length=100)),
                ('initiated_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ARCHIVING', 'Archivage en cours'), ('ARCHIVED', 'Archive validée'), ('CLEANING', 'Nettoyage des ressources en cours'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20)),
                ('archive_reference', models.CharField(blank=True, default='', max_length=255)),
                ('archive_version', models.CharField(blank=True, default='', max_length=20)),
                ('retention_policy', models.CharField(blank=True, default='', max_length=100)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('deletion_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='tenants_ten_tenant__d806a7_idx')],
            },
        ),
    ]
