# Generated by Django 5.1.7 on 2026-04-12 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_adresse_nationalite_patient_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitePhysique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'activité")),
                ('frequence', models.CharField(max_length=100, verbose_name='Fréquence')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_physiques', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Activité Physique',
                'verbose_name_plural': 'Activités Physiques',
            },
        ),
        migrations.CreateModel(
            name='Addiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'addiction")),
                ('debut', models.DateField(verbose_name='Date de début')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SEVRE', 'Sevré'), ('EN_COURS', 'En cours de sevrage')], max_length=20, verbose_name='Statut')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addictions', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Addiction',
                'verbose_name_plural': 'Addictions',
            },
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manifestation', models.CharField(max_length=255, verbose_name='Manifestation')),
                ('declencheur', models.CharField(max_length=255, verbose_name='Déclencheur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Allergie',
                'verbose_name_plural': 'Allergies',
            },
        ),
        migrations.CreateModel(
            name='DonneesCliniques',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groupe_sanguin', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='Groupe sanguin')),
                ('facteur_rhesus', models.CharField(choices=[('POSITIF', '+'), ('NEGATIF', '-')], max_length=10, verbose_name='Facteur rhésus')),
                ('electrophorese_hb', models.CharField(blank=True, max_length=50, null=True, verbose_name="Electrophorèse d'Hb")),
                ('poids', models.CharField(max_length=50, verbose_name='Poids')),
                ('taille', models.CharField(max_length=50, verbose_name='Taille')),
                ('pouls', models.CharField(max_length=50, verbose_name='Pouls')),
                ('taux_oxygene', models.CharField(max_length=50, verbose_name="Taux d'oxygène")),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_cliniques', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Données Cliniques',
                'verbose_name_plural': 'Données Cliniques',
            },
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la maladie')),
                ('debut', models.DateField(verbose_name='Date de début')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
            },
        ),
        migrations.CreateModel(
            name='ModeDeVie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moustiquaire', models.BooleanField(default=False, verbose_name='Dort sous moustiquaire')),
                ('animal_de_compagnie', models.BooleanField(default=False, verbose_name='A un animal de compagnie')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mode_de_vie', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Mode de Vie',
                'verbose_name_plural': 'Modes de Vie',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.TextField(verbose_name='Motif')),
                ('personnel_concerne', models.CharField(max_length=255, verbose_name='Personnel concerné')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('ANNULE', 'Annulé'), ('REPORTE', 'Reporté'), ('TERMINE', 'Terminé')], default='PROGRAMME', max_length=20, verbose_name='Statut')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_medicament', models.CharField(max_length=255, verbose_name='Nom du médicament')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('duree', models.CharField(max_length=100, verbose_name='Durée')),
                ('posologie', models.TextField(verbose_name='Posologie')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='patient_informations.maladie')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lieu', models.CharField(max_length=255, verbose_name='Lieu')),
                ('frequence', models.CharField(max_length=100, verbose_name='Fréquence')),
                ('duree', models.CharField(max_length=100, verbose_name='Durée')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
    ]
