# Generated by Django 5.1.7 on 2026-04-14 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_matricule'),
        ('patient_informations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MEDICAL', 'Médical'), ('FAMILIAL', 'Familial')], max_length=20, verbose_name="Type d'antécédent")),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'antécédent")),
                ('date', models.DateField(verbose_name="Date de l'antécédent")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Antécédent',
                'verbose_name_plural': 'Antécédents',
                'ordering': ['-date'],
            },
        ),
    ]
