# Generated by Django 5.1.7 on 2026-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_informations', '0002_antecedent'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneescliniques',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Température'),
        ),
        migrations.AddField(
            model_name='donneescliniques',
            name='tension_arterielle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tension artérielle'),
        ),
    ]
