"""
Django settings for service_personnel project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b_v@53@ta@o14^a4hop-o)zwe4)2!g4jr-stig_*@y*hwfh%n&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Phase 6 (Dynamic Database Routing) : DOIT rester en dernier pour
    # englober tout le cycle de la requête, y compris l'authentification
    # DRF qui établit le Tenant Context pendant le dispatch de la vue —
    # voir api/tenant_routing/middleware.py.
    'api.tenant_routing.middleware.TenantContextCleanupMiddleware',
]

# Configuration REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.GatewayHeaderAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'api.exceptions.fultang_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Service Personnel - Hôpital Fultang',
    'DESCRIPTION': (
        'Ce microservice gère l\'ensemble des ressources humaines et le '
        'personnel médical et administratif de l\'Hôpital Fultang.\n\n'
        '## ⚠️ Authentification requise\n'
        'Tous les endpoints nécessitent un **Bearer Token JWT** obtenu via la Gateway.\n\n'
        '1. Appelez `POST http://localhost:8080/auth/login` avec vos identifiants.\n'
        '2. Copiez l\'`access_token` retourné.\n'
        '3. Cliquez sur le bouton **Authorize 🔒** ci-dessous et collez le token.\n\n'
        'Il permet d\'effectuer les opérations CRUD sur tous les corps de métiers : '
        'Médecins, Infirmières, Pharmaciens, Laborantins, Réceptionnistes, '
        'Directeurs, Administrateurs et Comptables.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
    # Pointer le Swagger vers la Gateway avec le préfixe /personnel/
    'SERVERS': [
        {
            'url': 'http://localhost:8080/personnel',
            'description': 'API Gateway (Point d\'entrée principal — Auth JWT requise)',
        },
    ],
    # Définir le schéma de sécurité JWT Bearer
    'SECURITY': [{'BearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'BearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'Token JWT obtenu via POST /auth/login sur la Gateway (http://localhost:8080)',
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'CONTACT': {
        'name': 'Équipe de Développement Fultang',
        'email': 'support@fultang.local',
    },
    'LICENSE': {
        'name': 'Propriétaire',
    },
}

# CORS - Autoriser les autres microservices
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8001",
    "http://service-client:8000",
]

CORS_ALLOW_CREDENTIALS = True

# URL de base du microservice (pour service discovery)
MICROSERVICE_BASE_URL = 'http://localhost:8000'
MICROSERVICE_NAME = 'mon-microservice'

ROOT_URLCONF = 'service_personnel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'service_personnel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'service_personnel'),
        'USER': os.environ.get('POSTGRES_USER', 'admin'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
        'HOST': os.environ.get('POSTGRES_HOST', 'postgres'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# Phase 6 — Dynamic Database Routing.
# 'default' reste la base des tables système Django (auth, admin,
# sessions, contenttypes) ET du "pool non assigné" (tenant_id=None,
# Phase 3) — voir api/tenant_routing/router.py pour la logique complète.
DATABASE_ROUTERS = ['api.tenant_routing.router.TenantDatabaseRouter']

# Communication interne vers le Tenant Registry (tenant-service), pour
# résoudre "quelle base pour ce tenant + PERSONNEL ?" (Phase 5,
# TenantDatabase). Même jeton partagé que celui déjà utilisé par la
# Gateway pour /tenants/resolve/ (Phase 2.1) — service-personnel devient
# un second appelant de confiance du même mécanisme IsInternalService,
# aucun nouveau protocole introduit.
TENANT_SERVICE_URL = os.environ.get('TENANT_SERVICE_URL', 'http://fultang-tenant-web:8000')
TENANT_SERVICE_INTERNAL_TOKEN = os.environ.get('TENANT_SERVICE_INTERNAL_TOKEN', '')
TENANT_SERVICE_TIMEOUT_SECONDS = int(os.environ.get('TENANT_SERVICE_TIMEOUT_SECONDS', '5'))

# Cache TTL du mapping tenant → base (voir api/tenant_routing/cache.py).
TENANT_DB_CACHE_TTL_SECONDS = int(os.environ.get('TENANT_DB_CACHE_TTL_SECONDS', '300'))

# Cache TTL de l'état activé/désactivé d'un service fonctionnel (cycle de
# vie du tenant, Phase 2 — voir api/tenant_routing/functional_service_client.py).
# Volontairement plus court que TENANT_DB_CACHE_TTL_SECONDS : une
# désactivation de service doit se refléter rapidement (le PlatformAdmin
# s'attend à un effet quasi immédiat, contrairement à une information de
# connexion réseau qui change rarement).
FUNCTIONAL_SERVICE_CACHE_TTL_SECONDS = int(os.environ.get('FUNCTIONAL_SERVICE_CACHE_TTL_SECONDS', '60'))

# Connexions persistantes par tenant (voir api/tenant_routing/pool_registry.py
# pour la distinction avec un vrai pool multi-connexions). Configurable
# par environnement — jamais une valeur unique figée dans le code ;
# point d'extension pour une configuration PAR TENANT en Phase 9.
TENANT_DB_CONN_MAX_AGE = int(os.environ.get('TENANT_DB_CONN_MAX_AGE', '60'))

# Identifiants de connexion PostgreSQL utilisés pour TOUTES les bases
# tenant de ce service (pas de credential par tenant dans cette phase —
# aucun Secret Manager n'est encore implémenté dans FullTang, voir Phase
# 5 §6 et MULTITENANT_ARCHITECTURE.md). `TenantDatabase.secret_reference`
# n'est PAS utilisé pour se connecter ici : c'est une référence opaque
# réservée à un futur Secret Manager, pas un mécanisme fonctionnel.
TENANT_DB_USER = os.environ.get('TENANT_DB_USER', os.environ.get('POSTGRES_USER', 'admin'))
TENANT_DB_PASSWORD = os.environ.get('TENANT_DB_PASSWORD', os.environ.get('POSTGRES_PASSWORD', 'password'))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
