services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_personnel
    environment:
      POSTGRES_DB: service_personnel
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
