services:
  frontend:
    build: .
    container_name: fultang-frontend
    ports:
      - "5173:80"
    networks:
      - fultang_shared_network
    restart: always

networks:
  fultang_shared_network:
    name: fultang_shared_network
    external: true
