

export const AppRoutesPaths = {
    notFound: "*",
    adminHomePage: "/admin/home",
    adminServicesPage: "/admin/services",
    adminPersonnelPage: "/admin/personnel",
    adminChambresPage: "/admin/chambres",
    welcomePage: "/",
    loginPage: "/login",
    forgottenPasswordPage: "/forgotten-password",

    // Platform Admin (back-office plateforme, distinct des tenants)
    platformAdminLoginPage: "/platform-admin/login",
    platformAdminDashboardPage: "/platform-admin/dashboard",
    platformAdminEstablishmentsPage: "/platform-admin/establishments",
    platformAdminCreateTenantPage: "/platform-admin/establishments/new",
    platformAdminTenantDetailPage: "/platform-admin/establishments/:tenantId",
    platformAdminLogsPage: "/platform-admin/logs",

    doctorPage: "/doctor/waiting-room",
    laboratoryAssistantPage: "/laboratory-assistant/analyse",
    cashierPage: "/cashier/consultation-list",
    consultationsList: "/cashier/consultations-list",
    examsList: "/cashier/exams-list",
    hospitalisations: "/cashier/hospitalisations-list",
    financialReport: "/cashier/financial-report",
    helpCenter: "/cashier/help-center",
    specialistPage: "/specialist",
    specialistWaitingRoom: "/specialist/waiting-room",
    specialistPatientList: "/specialist/patients",
    specialistConsultationList: "/specialist/consultation-list",
    specialistAppointments: "/specialist/appointments",
    specialistExamList: "/specialist/exams-list",
    specialistHospitalized: "/specialist/hospitalized",
    specialistPatientDossier: "/specialist/patients/medical-folder/:id",
    nursePage: "/nurse/waiting-room",
    nurseWaitingRoomPage: "/nurse/waiting-room",
    nursePatientManagementPage: "/nurse/patient-management",
    nurseAppointmentsPage: "/nurse/appointments",
    nurseExamsPage: "/nurse/exams",
    nurseHospitalizationsPage: "/nurse/hospitalizations",
    nurseMedicalStaffsPage: "/nurse/medical-staff",
    consultationHistoryPage: "/nurse/patients/consultation-history/:id",
    helpCenterPage: "/help-center",
    patientDetailsPage: "/nurse/patients/take-parameters/:id",
    receptionistPage: "/receptionist/patients",
    receptionistMedicalStaffsPage: "/receptionist/medical-staffs",
    appointmentsPage: "/receptionist/appointments",
    receptionistConsultationsPage: "/receptionist/consultations",
    hospitalizedPatientsPage: "/receptionist/hospitalized",
    adminPatientListPage: "/admin/patient-list",
    addDrug: "/admin/add-drug",
    adminDrugsListPage: "/admin/drugs-list",
    addMedicalStaff: "/admin/add-medical-staff",
    adminMedicalStaffListPage: "/admin/medical-staff-list",
    adminConsultationListPage: "/admin/consultation-list",
    adminAppointmentsListPage: "/admin/appointments-list",
    addExam: "/admin/add-exam",
    adminExamsListPage: "/admin/exams-list",
    adminHospitalRoomPage: "/admin/room-list",
    adminFinancialReportsPage: "/admin/financial-report",
    adminConsultationDetailsPage: "/admin/consultation-list/details",
    laboratoryHistory: "/laboratory/exams-history",
    laboratoryCurrent: "/laboratory/current-exams",
    financialHistory: "/cashier/financial-history",
    doctorPatientList: "/doctor/patients",
    doctorConsultationList: "/doctor/consultation-list",
    doctorConsultationDetailsPage: "/doctor/consultation-list/details/:id",
    doctorAppointment: "/doctor/appointments",
    doctorConsultationHistory: "/doctor/consultation-history",
    doctorConsultationHistoryDetails: "/doctor/consultation-history/details/:id",
    doctorExamList: "/doctor/exams-list",
    doctorPatientMedicalFolderPage: "/doctor/patients/medical-folder/:id",

    laboratoryAssistantPage: "/laboratory-assistant/analyse",
    laboratoryReception: "/laboratory-assistant/reception",
    laboratoryAnalyse: "/laboratory-assistant/analyse",
    laboratoryResults: "/laboratory-assistant/results",
    laboratoryHistory: "/laboratory-assistant/history",

    // ComptaMatiere (Comptable Matière) routes
    comptaMatiereDashboard: "/compta-matiere/dashboard",
    comptaMatiereEmitNeed: "/compta-matiere/emit-need",
    comptaMatiereRegisterDelivery: "/compta-matiere/register-delivery",
    comptaMatiereDeliveryList: "/compta-matiere/delivery-list",
    comptaMatiereRegisterOutput: "/compta-matiere/register-output",
    comptaMatiereReports: "/compta-matiere/reports",
    comptaMatiereMaterialList: "/compta-matiere/material-list",
    comptaMatiereOutputList: "/compta-matiere/output-list",
    comptaMatiereInventoryArchives: "/compta-matiere/inventory-archives",

    // Director routes
    directorDashboard: "/director/dashboard",
    directorReports: "/director/reports",
    directorAudit: "/director/audit",

    // Pharmacist routes
    pharmacistPrescriptions: "/pharmacist/prescriptions",
    pharmacistDelivery: "/pharmacist/delivery",
    pharmacistMedicationList: "/pharmacist/medication-list",
    pharmacistEmitNeed: "/pharmacist/emit-need",
    pharmacistDailySales: "/pharmacist/daily-sales",
    pharmacistInventory: "/pharmacist/inventory",
    pharmacistReports: "/pharmacist/reports",

    // Old Pharmacy routes
    pharmacyHome: "/pharmacy/home",
    pharmacyNeeds: "/pharmacy/needs",
    pharmacyOperations: "/pharmacy/operations",
    pharmacyList: "/pharmacy/list",
    pharmacyDashboard: "/pharmacy/dashboard",

    // Accountant Module (New - from prototype)
    accountantHome: "/accountant/home",
    accountantQuittancesAValider: "/accountant/quittances/a-valider",
    accountantQuittancesValidees: "/accountant/quittances/validees",
    accountantEcritures: "/accountant/ecritures",
    accountantBalance: "/accountant/balance",
    accountantPlanComptable: "/accountant/plan-comptable",
    accountantRapports: "/accountant/rapports",
    
    accountantComptabilisation: "/accountant/comptabilisation",
    accountantSaisieEcriture: "/accountant/ecritures/saisie",
    accountantAchats: "/accountant/achats",
    accountantExercices: "/accountant/exercices-budgets",
    accountantAuditLog: "/accountant/audit",
    cashierCaisseQuotidienne: "/cashier/caisse",
    cashierDecaissements: "/cashier/decaissements",
    cashierQuittancesAValider: "/cashier/quittances/a-valider",
    cashierQuittancesValidees: "/cashier/quittances/validees",
    accountantFournisseurs: "/accountant/fournisseurs",
    accountantCheques: "/accountant/cheques",
    accountantPrestations: "/accountant/prestations",
}
