# Generated by Django 6.0.3 on 2026-04-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nb_etages', models.IntegerField()),
                ('date_construction', models.DateField()),
                ('responsable_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBatiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etages', to='infrastructures.batiment')),
            ],
        ),
        migrations.AddField(
            model_name='batiment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batiments', to='infrastructures.typebatiment'),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('capacite', models.IntegerField()),
                ('numero', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPEE', 'Occupée'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service'), ('RESERVEE', 'Réservée')], default='DISPONIBLE', max_length=50)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('etage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='infrastructures.etage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salles', to='infrastructures.typesalle')),
            ],
        ),
    ]
