# Generated by Django 5.1.7 on 2026-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='nb_places_disponibles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='tarif_journalier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typebatiment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typesalle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
