# Generated by Django 6.0.3 on 2026-04-02 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='comptablefinancier',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='comptablefinancier',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='comptablematiere',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='comptablematiere',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='directeur',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='directeur',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='infirmiere',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='infirmiere',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='laborantin',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='laborantin',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='pharmacien',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='pharmacien',
            name='salaire_de_base',
        ),
        migrations.RemoveField(
            model_name='receptionniste',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='receptionniste',
            name='salaire_de_base',
        ),
        migrations.AlterField(
            model_name='admin',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='comptablefinancier',
            name='niveau_accreditation',
            field=models.CharField(choices=[('TECHNICIEN_ASSISTANT', 'Technicien Assistant'), ('CADRE_COMPTABLE', 'Cadre Comptable'), ('EXPERT_COMPTABLE', 'Expert Comptable'), ('CERTIFICATIONS_PROFESSIONNELLES', 'Certifications Professionnelles'), ('AUTRE', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comptablefinancier',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='comptablefinancier',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='comptablematiere',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='comptablematiere',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='directeur',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='directeur',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='infirmiere',
            name='grade',
            field=models.CharField(choices=[('IDE', 'IDE'), ('ISP', 'ISP'), ('INFIRMIER_ASSISTANT_PRINCIPAL', 'Infirmier Assistant Principal'), ('INFIRMIER_ANESTHESISTE', 'Infirmier Anesthésiste'), ('INFIRMIER_BREVETE', 'Infirmier Breveté'), ('AUTRE', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='infirmiere',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='infirmiere',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='laborantin',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='laborantin',
            name='specialite_labo',
            field=models.CharField(choices=[('PARASITOLOGIE_MYCOLOGIE', 'Parasitologie Mycologie'), ('HEMATOLOGIE', 'Hématologie'), ('BIOCHIMIE_CLINIQUE', 'Biochimie Clinique'), ('BACTERIOLOGIE_VIROLOGIE', 'Bactériologie Virologie'), ('IMMUNOLOGIE_SERO_IMMUNOLOGIE', 'Immunologie Séro-Immunologie'), ('AUTRE', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='laborantin',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='receptionniste',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service'),
        ),
        migrations.AlterField(
            model_name='receptionniste',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20),
        ),
    ]
