# Generated by Django 6.0.3 on 2026-05-24 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_admin_id_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedecinGeneraliste',
            fields=[
                ('id_personnel', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('date_embauche', models.DateField()),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Autre', 'Autre')], default='Actif', max_length=20)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('numero_ordre', models.CharField(help_text="Numéro d'inscription à l'Ordre National des Médecins du Cameroun", max_length=50, verbose_name="Numéro d'ordre")),
                ('zone_couverte', models.CharField(blank=True, default='', help_text='Secteur ou quartier de rattachement du médecin généraliste', max_length=200, verbose_name='Zone couverte')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_personnels', to='api.service')),
            ],
            options={
                'verbose_name': 'Médecin Généraliste',
                'verbose_name_plural': 'Médecins Généralistes',
            },
        ),
    ]
