# Generated by Django 6.0.3 on 2026-06-29 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medecingeneraliste'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='chef_service_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_service',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comptablefinancier',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comptablematiere',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='directeur',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infirmiere',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laborantin',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receptionniste',
            name='id_personnel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
