# Generated by Django 6.0.3 on 2026-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_service_chef_service_id_service_desc_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="comptablefinancier",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="comptablematiere",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="directeur",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="infirmiere",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="laborantin",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="medecin",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="medecingeneraliste",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacien",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="receptionniste",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="admin",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="comptablefinancier",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="comptablefinancier",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="comptablematiere",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="comptablematiere",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="directeur",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="directeur",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="infirmiere",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="infirmiere",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="laborantin",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="laborantin",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="medecin",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="medecin",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="medecingeneraliste",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="medecingeneraliste",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="pharmacien",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="pharmacien",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="receptionniste",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="receptionniste",
            name="matricule",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="admin",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"), name="api_admin_unique_email_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="admin",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_admin_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="comptablefinancier",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_comptablefinancier_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="comptablefinancier",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_comptablefinancier_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="comptablematiere",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_comptablematiere_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="comptablematiere",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_comptablematiere_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="directeur",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_directeur_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="directeur",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_directeur_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="infirmiere",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_infirmiere_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="infirmiere",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_infirmiere_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborantin",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_laborantin_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborantin",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_laborantin_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="medecin",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_medecin_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="medecin",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_medecin_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacien",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_pharmacien_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacien",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_pharmacien_unique_matricule_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="receptionniste",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "email"),
                name="api_receptionniste_unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="receptionniste",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "matricule"),
                name="api_receptionniste_unique_matricule_per_tenant",
            ),
        ),
    ]
