# Generated by Django 6.0.3 on 2026-04-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique (ex: CAT-MED, CAT-FOUR)', max_length=20, unique=True, verbose_name='Code catégorie')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_categorie', models.CharField(choices=[('achat', 'Achat'), ('service', 'Service'), ('salaire', 'Salaire'), ('charge_sociale', 'Charge Sociale'), ('investissement', 'Investissement'), ('fonctionnement', 'Fonctionnement'), ('autre', 'Autre')], max_length=20, verbose_name='Type de catégorie')),
                ('compte_comptable', models.ForeignKey(help_text='Compte de charge OHADA associé (classe 6)', on_delete=django.db.models.deletion.PROTECT, related_name='categories_sortie', to='comptabilite.comptecomptable', verbose_name='Compte comptable OHADA')),
            ],
            options={
                'verbose_name': 'Catégorie de Sortie',
                'verbose_name_plural': 'Catégories de Sortie',
                'ordering': ['code'],
            },
        ),
    ]
