# Generated by Django 6.0.3 on 2026-04-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_auditlog'),
        ('sorties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('service_demandeur_id', models.IntegerField(blank=True, help_text='# EXT', null=True)),
                ('demandeur_id', models.IntegerField(blank=True, help_text='# EXT', null=True)),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=15)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('est_banque_de_sang', models.BooleanField(default=False, verbose_name='Banque de sang (prioritaire)')),
                ('avis_comptable', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('favorable', 'Favorable'), ('defavorable', 'Défavorable')], default='en_attente', max_length=15, null=True)),
                ('commentaire_budgetaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('evaluee', 'Évaluée'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='soumise', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Demande d'Achat",
                'verbose_name_plural': "Demandes d'Achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide_comptable', 'Validé comptable'), ('approuve_directeur', 'Approuvé directeur'), ('envoye', 'Envoyé')], default='brouillon', max_length=25)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande_achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='sorties.demandeachat')),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=100, verbose_name='Numéro facture fournisseur')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('est_payee', models.BooleanField(default=False)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='sorties.boncommande')),
            ],
            options={
                'verbose_name': 'Facture Fournisseur',
                'verbose_name_plural': 'Factures Fournisseurs',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('niu', models.CharField(blank=True, max_length=50, verbose_name='NIU')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rib', models.CharField(blank=True, max_length=100, verbose_name='RIB')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='comptabilite.comptecomptable', verbose_name='Compte fournisseur (401xxx)')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='sorties.fournisseur'),
        ),
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sorties.boncommande')),
            ],
            options={
                'verbose_name': 'Ligne Bon de Commande',
                'verbose_name_plural': 'Lignes Bon de Commande',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sorties.facture')),
            ],
            options={
                'verbose_name': 'Ligne Facture',
                'verbose_name_plural': 'Lignes Facture',
            },
        ),
        migrations.CreateModel(
            name='OrdrePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_sortie', models.CharField(choices=[('fournisseur', 'Fournisseur'), ('salaire', 'Salaire'), ('remboursement', 'Remboursement'), ('charge', 'Charge')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('caisse', 'Caisse'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide_comptable', 'Validé comptable'), ('approuve_directeur', 'Approuvé directeur'), ('execute', 'Exécuté')], default='brouillon', max_length=25)),
                ('est_comptabilise', models.BooleanField(default=False)),
                ('beneficiaire', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_paiement', to='sorties.facture')),
            ],
            options={
                'verbose_name': 'Ordre de Paiement',
                'verbose_name_plural': 'Ordres de Paiement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('personnel_id', models.IntegerField(blank=True, help_text='# EXT', null=True)),
                ('nom_personnel', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retenue_cnps', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retenue_impots', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deduction_ecart_caisse', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Déduction écart caisse')),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('est_paye', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement Salaire',
                'verbose_name_plural': 'Paiements Salaires',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee', 'personnel_id')},
            },
        ),
        migrations.CreateModel(
            name='ChargeSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_charge', models.CharField(choices=[('cnps', 'CNPS'), ('assurance', 'Assurance'), ('impots', 'Impôts')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('paiement_salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_sociales', to='sorties.paiementsalaire')),
            ],
            options={
                'verbose_name': 'Charge Sociale',
                'verbose_name_plural': 'Charges Sociales',
            },
        ),
    ]
