# Generated by Django 6.0.4 on 2026-05-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0002_demandeachat_boncommande_facture_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='sorties.fournisseur', verbose_name='Fournisseur'),
        ),
    ]
