# Generated by Django 6.0.6 on 2026-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0003_add_fournisseur_to_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='demandeur_id',
            field=models.CharField(blank=True, help_text='# EXT (UUID ou id personnel)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='service_demandeur_id',
            field=models.CharField(blank=True, help_text='# EXT (UUID ou id personnel)', max_length=64, null=True),
        ),
    ]
