# Generated by Django 6.0.6 on 2026-07-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0004_alter_demandeachat_demandeur_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='est_comptabilisee',
            field=models.BooleanField(default=False, help_text='Écriture de charge (Débit 6xx / Crédit 401) générée.'),
        ),
    ]
