# Generated by Django 5.1.7 on 2026-04-12 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.TextField(verbose_name='Motif de la consultation')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure')),
                ('doctor_id', models.UUIDField(verbose_name='ID du Médecin en charge')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patient.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé du diagnostic')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('niveau_certitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Niveau de certitude')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='medical_workflow.consultation')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'examen")),
                ('motif', models.TextField(verbose_name="Motif de l'examen")),
                ('anatomie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zone anatomique')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REALISE', 'Réalisé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='medical_workflow.consultation')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.UUIDField(verbose_name='ID de la Chambre')),
                ('doctor_id', models.UUIDField(verbose_name='ID du Médecin en charge')),
                ('motif', models.TextField(verbose_name="Motif d'hospitalisation")),
                ('duree_prevue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Durée prévue')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminée')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
            },
        ),
        migrations.CreateModel(
            name='MedicamentPrescrit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du médicament')),
                ('quantite', models.CharField(max_length=100, verbose_name='Quantité')),
                ('type_medicament', models.CharField(max_length=100, verbose_name='Type')),
                ('posologie', models.TextField(verbose_name='Posologie')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_workflow.consultation')),
            ],
            options={
                'verbose_name': 'Médicament Prescrit',
                'verbose_name_plural': 'Médicaments Prescrits',
            },
        ),
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_id', models.UUIDField(verbose_name='ID du Médecin responsable')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('resultats', models.TextField(verbose_name='Résultats détaillés')),
                ('interpretation', models.TextField(blank=True, null=True, verbose_name='Interprétation')),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='medical_workflow.examen')),
            ],
            options={
                'verbose_name': "Résultat d'Examen",
                'verbose_name_plural': "Résultats d'Examens",
            },
        ),
        migrations.CreateModel(
            name='SoinAdministre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responsible_person_id', models.UUIDField(verbose_name='ID du Personnel responsable')),
                ('motif', models.TextField(verbose_name='Motif du soin')),
                ('type_soin', models.CharField(max_length=100, verbose_name='Type de soin')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du soin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_recus', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Soin Administré',
                'verbose_name_plural': 'Soins Administrés',
            },
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du symptôme')),
                ('localisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('frequence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fréquence')),
                ('duree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Durée')),
                ('evolution', models.TextField(blank=True, null=True, verbose_name='Évolution')),
                ('activite_declencheuse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activité déclencheuse')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptomes', to='medical_workflow.consultation')),
            ],
            options={
                'verbose_name': 'Symptôme',
                'verbose_name_plural': 'Symptômes',
            },
        ),
    ]
