# Generated by Django 5.1.7 on 2026-04-14 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_workflow', '0001_initial'),
        ('patient', '0003_alter_patient_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin_charge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Médecin en charge'),
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif_visite', models.TextField(verbose_name='Motif global de la visite')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name="Date et Heure d'ouverture")),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='patient.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='visite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medical_workflow.visite', verbose_name='Visite'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='visite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='medical_workflow.visite'),
        ),
        migrations.AddField(
            model_name='soinadministre',
            name='visite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='medical_workflow.visite'),
        ),
    ]
