# Generated by Django 5.1.7 on 2026-04-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_workflow', '0002_remove_consultation_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalisation',
            old_name='room_id',
            new_name='chambre',
        ),
    ]
