# Generated by Django 5.1.7 on 2026-04-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_workflow', '0003_rename_room_id_hospitalisation_chambre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalisation',
            old_name='chambre',
            new_name='room_id',
        ),
    ]
