# Generated by Django 5.1.7 on 2026-05-25 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_workflow', '0004_rename_chambre_hospitalisation_room_id'),
        ('patient', '0003_alter_patient_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentprescrit',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('ANOMALIE', 'Anomalie signalée'), ('DELIVREE', 'Délivrée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PRELEVE', 'Prélèvement effectué'), ('REALISE', 'Résultats saisis (Non validés)'), ('VALIDE', 'Résultats validés')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='AnomaliePrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pharmacien_id', models.UUIDField(verbose_name='ID du Pharmacien')),
                ('commentaire', models.TextField(verbose_name="Commentaire / Motif de l'anomalie")),
                ('alternative_proposee', models.TextField(blank=True, null=True, verbose_name='Alternative proposée')),
                ('statut', models.CharField(choices=[('NON_RESOLUE', 'Non résolue'), ('RESOLUE', 'Résolue')], default='NON_RESOLUE', max_length=20, verbose_name='Statut')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='medical_workflow.medicamentprescrit')),
            ],
            options={
                'verbose_name': 'Anomalie de Prescription',
                'verbose_name_plural': 'Anomalies de Prescription',
            },
        ),
        migrations.CreateModel(
            name='ConciliationMedicamenteuse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pharmacien_id', models.UUIDField(verbose_name='ID du Pharmacien')),
                ('type_conciliation', models.CharField(choices=[('ADMISSION', "À l'admission"), ('SORTIE', 'À la sortie')], default='ADMISSION', max_length=20)),
                ('liste_medicaments', models.TextField(verbose_name='Liste des médicaments antérieurs/de sortie')),
                ('divergences_identifiees', models.TextField(blank=True, null=True, verbose_name='Divergences non intentionnelles')),
                ('date_conciliation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliations', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Conciliation Médicamenteuse',
                'verbose_name_plural': 'Conciliations Médicamenteuses',
            },
        ),
        migrations.CreateModel(
            name='DelivranceMedicament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pharmacien_id', models.UUIDField(verbose_name='ID du Pharmacien')),
                ('quantite_delivree', models.CharField(max_length=100, verbose_name='Quantité délivrée')),
                ('date_delivrance', models.DateTimeField(auto_now_add=True)),
                ('mode_delivrance', models.CharField(choices=[('NOMINATIF', 'Nominatif (Dose par dose)'), ('GLOBAL', 'Global (Dotation service)')], default='NOMINATIF', max_length=50)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivrances', to='medical_workflow.medicamentprescrit')),
            ],
            options={
                'verbose_name': 'Délivrance de Médicament',
                'verbose_name_plural': 'Délivrances de Médicaments',
            },
        ),
        migrations.CreateModel(
            name='Prelevement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('laborantin_id', models.UUIDField(verbose_name='ID du Laborantin')),
                ('type_prelevement', models.CharField(max_length=100, verbose_name='Type de prélèvement (ex: Sang, Urine)')),
                ('date_prelevement', models.DateTimeField(auto_now_add=True)),
                ('code_barre', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code barre / Numéro de tube')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelevements', to='medical_workflow.examen')),
            ],
            options={
                'verbose_name': 'Prélèvement',
                'verbose_name_plural': 'Prélèvements',
            },
        ),
        migrations.CreateModel(
            name='ValeurCritique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('laborantin_id', models.UUIDField(verbose_name='ID du Laborantin ayant signalé')),
                ('valeur_mesuree', models.CharField(max_length=255, verbose_name='Valeur mesurée')),
                ('seuil_alerte', models.CharField(max_length=255, verbose_name="Seuil d'alerte dépassé")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire / Action recommandée')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('medecin_notifie', models.BooleanField(default=False, verbose_name='Médecin notifié')),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_critiques', to='medical_workflow.resultatexamen')),
            ],
            options={
                'verbose_name': 'Valeur Critique',
                'verbose_name_plural': 'Valeurs Critiques',
            },
        ),
    ]
