# Generated by Django 5.1.7 on 2026-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_workflow', '0005_medicamentprescrit_statut_alter_examen_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='doctor_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID du Médecin en charge'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='room_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID de la Chambre'),
        ),
    ]
