# Generated by Django 5.1.7 on 2026-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_workflow', '0006_alter_hospitalisation_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Service d'accueil"),
        ),
    ]
