# Generated by Django 6.0.3 on 2026-04-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0003_auditlog'),
        ('sorties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Solde d'ouverture")),
                ('solde_physique', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Solde physique (comptage réel)')),
                ('solde_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde théorique (calculé)')),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Écart')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('caissier_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Caissier')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caisse Journalière',
                'verbose_name_plural': 'Caisses Journalières',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepenseMenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('motif', models.CharField(max_length=300, verbose_name='Motif')),
                ('caissier_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Caissier')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='caisse.caissejournaliere', verbose_name='Caisse journalière')),
                ('categorie_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_menues', to='sorties.categoriesortie', verbose_name='Catégorie de sortie')),
            ],
            options={
                'verbose_name': 'Dépense Menue',
                'verbose_name_plural': 'Dépenses Menues',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InventaireCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('recettes_enregistrees', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Recettes enregistrées')),
                ('recettes_attendues', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Recettes attendues')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart')),
                ('ecart_justifie', models.BooleanField(default=False, verbose_name='Écart justifié')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('caissier_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Caissier')),
                ('comptable_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Comptable')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('clos', 'Clos')], default='ouvert', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventaire de Caisse',
                'verbose_name_plural': 'Inventaires de Caisse',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, help_text='Auto-généré : QT-YYYY-NNNNN', max_length=20, unique=True, verbose_name='Numéro de quittance')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant total')),
                ('motif', models.CharField(max_length=300, verbose_name='Motif')),
                ('type_recette', models.CharField(choices=[('consultation', 'Consultation'), ('hospitalisation', 'Hospitalisation'), ('laboratoire', 'Laboratoire'), ('pharmacie', 'Pharmacie'), ('imagerie', 'Imagerie'), ('chirurgie', 'Chirurgie'), ('autre', 'Autre')], max_length=20, verbose_name='Type de recette')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte Bancaire'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement Bancaire'), ('assurance', 'Assurance')], max_length=20, verbose_name='Mode de paiement')),
                ('est_validee', models.BooleanField(default=True, verbose_name='Validée par le caissier')),
                ('est_urgence', models.BooleanField(default=False, verbose_name='Urgence (paiement différé)')),
                ('est_comptabilisee', models.BooleanField(default=False, verbose_name='Comptabilisée')),
                ('est_assure', models.BooleanField(default=False, verbose_name='Patient assuré')),
                ('taux_couverture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux couverture (%)')),
                ('montant_assurance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Part assurance')),
                ('montant_patient', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Part patient')),
                ('assurance_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Assurance')),
                ('caissier_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Caissier')),
                ('patient_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Patient')),
                ('session_id', models.IntegerField(blank=True, help_text='# EXT', null=True, verbose_name='ID Session')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compte_tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quittances_tiers', to='comptabilite.comptecomptable', verbose_name='Compte tiers')),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quittances', to='comptabilite.exercicecomptable', verbose_name='Exercice comptable')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quittances', to='comptabilite.journal', verbose_name='Journal comptable')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PaiementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=10, verbose_name='Opérateur')),
                ('numero_payant', models.CharField(max_length=20, verbose_name='Numéro du payant')),
                ('reference_transaction', models.CharField(max_length=100, verbose_name='Référence transaction')),
                ('quittance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_mobile', to='caisse.quittance', verbose_name='Quittance')),
            ],
            options={
                'verbose_name': 'Paiement Mobile',
                'verbose_name_plural': 'Paiements Mobile',
            },
        ),
        migrations.CreateModel(
            name='PaiementCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatre_derniers_chiffres', models.CharField(max_length=4, verbose_name='4 derniers chiffres')),
                ('reference_transaction', models.CharField(max_length=100, verbose_name='Référence transaction')),
                ('id_terminal', models.CharField(max_length=50, verbose_name='ID Terminal')),
                ('quittance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_carte', to='caisse.quittance', verbose_name='Quittance')),
            ],
            options={
                'verbose_name': 'Paiement Carte',
                'verbose_name_plural': 'Paiements Carte',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro de chèque')),
                ('banque', models.CharField(max_length=100, verbose_name='Banque')),
                ('titulaire', models.CharField(max_length=200, verbose_name='Titulaire')),
                ('est_encaisse', models.BooleanField(default=False, verbose_name='Encaissé')),
                ('date_encaissement', models.DateField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('quittance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='caisse.quittance', verbose_name='Quittance')),
            ],
            options={
                'verbose_name': 'Chèque',
                'verbose_name_plural': 'Chèques',
            },
        ),
        migrations.CreateModel(
            name='VirementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque_emettrice', models.CharField(max_length=100, verbose_name='Banque émettrice')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence virement')),
                ('date_virement', models.DateField(verbose_name='Date du virement')),
                ('quittance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virement', to='caisse.quittance', verbose_name='Quittance')),
            ],
            options={
                'verbose_name': 'Virement Bancaire',
                'verbose_name_plural': 'Virements Bancaires',
            },
        ),
    ]
