# Generated by Django 5.1.7 on 2026-04-11 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Unique')),
                ('matricule', models.CharField(max_length=7, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('statut_matrimonial', models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('VEUF', 'Veuf(ve)'), ('DIVORCE', 'Divorcé(e)')], max_length=20, verbose_name='Statut matrimonial')),
                ('courriel', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Courriel')),
                ('numero_securite_sociale', models.CharField(max_length=50, unique=True, verbose_name='Numéro de sécurité sociale')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='Photo')),
                ('nombre_enfants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
