# Generated by Django 5.1.7 on 2026-04-12 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pays', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('rue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rue / Rue secondaire')),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Postal')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Nationalité',
                'verbose_name_plural': 'Nationalités',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_patient', to='patient.adresse'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationalites',
            field=models.ManyToManyField(blank=True, related_name='patients', to='patient.nationalite'),
        ),
        migrations.CreateModel(
            name='PersonneAPrevenir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('adresse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_urgence', to='patient.adresse')),
            ],
            options={
                'verbose_name': 'Personne à Prévenir',
                'verbose_name_plural': 'Personnes à Prévenir',
            },
        ),
        migrations.CreateModel(
            name='LienParente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('FRERE_SOEUR', 'Frère / Sœur'), ('CONJOINT', 'Conjoint(e)'), ('AMI', 'Ami(e)'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de relation')),
                ('relation_autre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Précision si autre')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('personne_a_prevenir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.personneaprevenir')),
            ],
            options={
                'verbose_name': 'Lien de Parenté',
                'verbose_name_plural': 'Liens de Parenté',
                'unique_together': {('patient', 'personne_a_prevenir')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEPHONE', 'Téléphonique')], max_length=20, verbose_name='Type de contact')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patient.patient')),
                ('personne_a_prevenir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patient.personneaprevenir')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='personnes_a_prevenir',
            field=models.ManyToManyField(related_name='patients_secours', through='patient.LienParente', to='patient.personneaprevenir'),
        ),
    ]
