# Generated by Django 5.1.7 on 2026-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_adresse_nationalite_patient_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='matricule',
            field=models.CharField(blank=True, max_length=7, unique=True, verbose_name='Matricule'),
        ),
    ]
